// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhm_Z5m6FZUevcOj78d84QYeEMOWJMGxA',
    appId: '1:1006763199056:web:7dbdb557cfeb8649f65f55',
    messagingSenderId: '1006763199056',
    projectId: 'chat-app-f9e29',
    authDomain: 'chat-app-f9e29.firebaseapp.com',
    storageBucket: 'chat-app-f9e29.appspot.com',
    measurementId: 'G-TMT967YDDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbgjpI9Rv8kr3axu062v_fL1pjBIIglOc',
    appId: '1:1006763199056:android:b8cb950a70a7bee9f65f55',
    messagingSenderId: '1006763199056',
    projectId: 'chat-app-f9e29',
    storageBucket: 'chat-app-f9e29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvuRa2uFkVILo3ds4B008IPXKxgyOB6N8',
    appId: '1:1006763199056:ios:6a8892e59f83a7f6f65f55',
    messagingSenderId: '1006763199056',
    projectId: 'chat-app-f9e29',
    storageBucket: 'chat-app-f9e29.appspot.com',
    iosBundleId: 'com.example.studyConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvuRa2uFkVILo3ds4B008IPXKxgyOB6N8',
    appId: '1:1006763199056:ios:6a8892e59f83a7f6f65f55',
    messagingSenderId: '1006763199056',
    projectId: 'chat-app-f9e29',
    storageBucket: 'chat-app-f9e29.appspot.com',
    iosBundleId: 'com.example.studyConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhm_Z5m6FZUevcOj78d84QYeEMOWJMGxA',
    appId: '1:1006763199056:web:1673a14c47ea93aef65f55',
    messagingSenderId: '1006763199056',
    projectId: 'chat-app-f9e29',
    authDomain: 'chat-app-f9e29.firebaseapp.com',
    storageBucket: 'chat-app-f9e29.appspot.com',
    measurementId: 'G-QBPCWFSTNC',
  );
}
